# Airflow DAG Generation: Evaluation

This notebook evaluates the quality of Airflow DAGs generated by different models, comparing a baseline model (Qwen 2.5 1.5B Instruct) against a fine-tuned version.


### TL;DR: Fine-Tuned Model Performance
The fine-tuning succeeded in teaching the model the vocabulary of Airflow but regressed in its ability to follow instructions and write valid code.

*The Good*: It knows the tools The model learned to be idiomatic. Instead of writing generic, simple Python scripts like the baseline, it correctly attempts to use specialized Airflow Operators (e.g., SnowflakeOperator) for specific tasks. It knows which tools are supposed to be used.

*The Bad*: It less prone to "thinking"

- It memorized the training data so aggressively that it ignores your prompt. If you ask for "12 records" or "cocktail recipes," it ignores you and pastes the "20 records" or "employee data" it saw during training.
-  Syntax errors spiked to 26%. It tries to write complex, import-heavy code but often gets the implementation details wrong or forgets basic Python syntax in the process.
- It invents operators that sound plausible (correct naming convention) but don't exist, and it frequently breaks production by importing internal testing modules it saw in the repo.

## 1. Setup and Configuration

In [1]:
import json
import glob
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
from typing import List, Dict, Any
import re

# hf
from datasets import load_dataset

# Import from installed packages
from research.lib.batch_processor import ClaudeBatchProcessor
from airflow_net.validation import DAGValidator

# Set visualization style
sns.set_theme(style="whitegrid", context="notebook", palette="viridis")

In [2]:
# API Key Configuration
import os

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')

if not ANTHROPIC_API_KEY:
    print("WARNING: No ANTHROPIC_API_KEY found in environment. LLM evaluation steps will be skipped.")
    print("To enable LLM evaluation, set the ANTHROPIC_API_KEY environment variable.")

## 2. Load Data
We load the generated DAGs from the JSONL artifacts produced by the inference step and the test dataset containing the ground truth DAG files.

In [11]:
# Define paths to artifacts (relative to notebook location)
ARTIFACTS_DIR = Path("../../artifacts/finetuning/01_inference_results").resolve()

print(f"Looking for artifacts in: {ARTIFACTS_DIR}")

# Find latest inference files
base_files = list(ARTIFACTS_DIR.glob("base_model_outputs*.jsonl"))
finetuned_files = list(ARTIFACTS_DIR.glob("finetuned_model_outputs*.jsonl"))

if not base_files or not finetuned_files:
    print("WARNING: Could not find one or both inference result files.")
    print(f"Available files: {list(ARTIFACTS_DIR.glob('*.jsonl'))}")
    BASE_MODEL_FILE = None
    FINETUNED_MODEL_FILE = None
else:
    # Take the most recent one
    BASE_MODEL_FILE = sorted(base_files)[-1]
    FINETUNED_MODEL_FILE = sorted(finetuned_files)[-1]
    print(f"Selected Baseline: {BASE_MODEL_FILE.name}")
    print(f"Selected Fine-tuned: {FINETUNED_MODEL_FILE.name}")

Looking for artifacts in: /Users/andreatamburri/Desktop/airflowNet/research/artifacts/finetuning/01_inference_results
Selected Baseline: base_model_outputs_20260108.jsonl
Selected Fine-tuned: finetuned_model_outputs_20260108.jsonl

In [12]:
def load_jsonl(file_path):
    """Load JSONL file and extract code from messages format"""
    if not file_path or not file_path.exists():
        return []
    data = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                entry = json.loads(line)
                # Extract assistant content from messages
                messages = entry.get('messages', [])
                user_content = ''
                assistant_content = ''
                
                for msg in messages:
                    if msg['role'] == 'user':
                        user_content = msg['content']
                    elif msg['role'] == 'assistant':
                        assistant_content = msg['content']
                    if msg['role'] == 'system':
                        system_content = msg['content']
                
                data.append({
                    'system': system_content,
                    'prompt': user_content,
                    'code': assistant_content,
                    'metadata': entry.get('metadata', {})
                })
    return data

baseline_data = load_jsonl(BASE_MODEL_FILE)
finetuned_data = load_jsonl(FINETUNED_MODEL_FILE)

print(f"Loaded {len(baseline_data)} baseline samples.")
print(f"Loaded {len(finetuned_data)} fine-tuned samples.")

Loaded 412 baseline samples.
Loaded 412 fine-tuned samples.

In [13]:
def parse_hf_ds(dataset):
    """Convert HuggingFace dataset to the same structure as load_jsonl function"""
    data = []

    for entry in dataset:
        messages = entry.get('messages', [])
        system_content = ''
        user_content = ''
        assistant_content = ''

        for msg in messages:
            if msg['role'] == 'system':
                system_content = msg['content']
            elif msg['role'] == 'user':
                user_content = msg['content']
            elif msg['role'] == 'assistant':
                assistant_content = msg['content']

        data.append({
            'system': system_content,
            'prompt': user_content,
            'code': assistant_content,
            'metadata': entry.get('metadata', {})
        })

    return data

dataset = load_dataset(
    "andrea-t94/airflow-dag-dataset",
    split="test",
    download_mode="reuse_cache_if_exists"  # Use cached version if available
)

ground_data = parse_hf_ds(dataset)
print(f"Loaded {len(ground_data)} ground truth samples.")

Generating train split:   0%|          | 0/7414 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/412 [00:00<?, ? examples/s]

Generating eval split:   0%|          | 0/412 [00:00<?, ? examples/s]

Loaded 412 ground truth samples.

## 3. Parser-Based Evaluation: fine-tuned model regression

 While the **Baseline** and **Ground Truth** models maintain high reliability with syntax success rates of **~95%**, the **Fine-tuned** model shows a significant decline, dropping to **~72%**. The errors are primarily fundamental Python syntax violations.

---

#### 1. Token Delimiter Mismatch (Parentheses, Brackets, & Strings)

The most prevalent failure mode involves the model's inability to maintain the structural integrity of complex code blocks.

* Frequent occurrences of unmatched brackets (e.g., `closing parenthesis ']' does not match opening parenthesis '{'`) and unterminated string literals.
* **Possible cause:** As the fine-tuned model attempts to generate more "idiomatic" and verbose Airflow code, it loses track of the Python stack, leading to truncated or malformed code structures that fail basic parsing.

#### 2. Regression in Foundational Python Syntax

The fine-tuning process appears to have caused "catastrophic forgetting" regarding basic Python rules that were handled correctly by the baseline.

* Generation of invalid Python literals (e.g., `invalid decimal literal`) and incorrect assignment syntax (e.g., using `=` instead of `==` in comparisons or malformed indentation).
* **Possible ause:** By over-optimizing for specific Airflow DSL patterns found in the training data, the model's general-purpose Python reasoning has degraded. It prioritizes the "shape" of an Airflow task over the fundamental syntax requirements of the Python language itself.

In [ ]:
def extract_code(text):
    """Extract python code block from sample."""
    if "```python" in text:
        return text.split("```python")[1].split("```")[0].strip()
    elif "```" in text:
        return text.split("```")[1].strip()
    return text.strip()

def evaluate_parser_results(data, model_name):
    """Evaluate DAG code using the DAGValidator"""
    results = []
    validator = DAGValidator()
    
    for entry in data:
        raw_code = entry.get('code', '')
        code = extract_code(raw_code)
        
        # Use DAGValidator.validate_content which returns List[ValidationError]
        errors = validator.validate_content(code, source_name="<generated>")
        
        # Extract error information
        is_valid = len(errors) == 0
        error_messages = [str(e) for e in errors]
        error_types = [e.error_type for e in errors]
        
        results.append({
            'model': model_name,
            'is_valid': is_valid,
            'error_count': len(errors),
            'errors': '; '.join(error_messages) if error_messages else '',
            'has_syntax_error': any('SYNTAX_ERROR' in et or 'PARSE_ERROR' in et for et in error_types),
            'has_duplicate_task': any('DUPLICATE_TASK_ID' in et for et in error_types),
            'has_invalid_task_id': any('INVALID_TASK_ID' in et for et in error_types),
            'has_circular_dependency': any('CIRCULAR_DEPENDENCY' in et for et in error_types)
        })
    return pd.DataFrame(results)

df_ground = evaluate_parser_results(ground_data, 'Ground')
df_base = evaluate_parser_results(baseline_data, 'Baseline')
df_fine = evaluate_parser_results(finetuned_data, 'Fine-tuned')
df_parser = pd.concat([df_ground, df_base, df_fine], ignore_index=True)

# Display summary statistics
summary = df_parser.groupby('model').agg(
    valid_rate=('is_valid', 'mean'),
    syntax_errors=('has_syntax_error', 'mean'),
    duplicate_tasks=('has_duplicate_task', 'mean'),
    invalid_task_ids=('has_invalid_task_id', 'mean'),
    circular_deps=('has_circular_dependency', 'mean')
) * 100

print("Parser Evaluation Results (%):")
display(summary.round(2))
df_parser.to_csv("parser_eval.csv", index=False)

Parser Evaluation Results (%):

,valid_rate,syntax_errors,duplicate_tasks,invalid_task_ids,circular_deps
model,,,,,
Baseline,95.39,4.13,0.24,0.0,0.24
Fine-tuned,71.84,25.97,1.21,0.0,0.73
Ground,94.66,1.94,0.73,0.0,0.24

## 4. LLM-Based Evaluation with Claude

To complement the parser-based structural analysis, we employ Claude Sonnet 4.5 as an LLM judge to evaluate semantic quality across three critical dimensions:

### Evaluation Metrics

**1. Idiomatic Airflow Usage (0/1 Binary Score)**
- **Pass (1):** Code uses provider-specific operators designed for the task (e.g., `SnowflakeOperator`, `S3Operator`)
- **Fail (0):** Code wraps logic in generic `PythonOperator` with hooks instead of using native operators
- **Rationale:** Idiomatic Airflow leverages the rich ecosystem of 100+ provider packages with purpose-built operators

**2. No Hallucination/Leakage (0/1 Binary Score)**
- **Pass (1):** Clean, production-ready code using only standard Airflow libraries
- **Fail (0):** Code imports internal testing modules (e.g., `from tests_common.test_utils.system_tests`) or fabricates non-existent APIs
- **Rationale:** Model hallucinations indicate training data contamination or knowledge gaps that would cause runtime failures

**3. Instruction Adherence (0/1 Binary Score)**
- **Pass (1):** Generated DAG fully implements the requested business logic
- **Fail (0):** Missing key requirements from the user instruction
- **Rationale:** Measures the model's ability to follow specifications accurately

### Key Findings

The evaluation reveals a nuanced performance profile for the fine-tuned model:

**Strengths:**
- **Airflow Idioms:** Fine-tuned model significantly outperforms the baseline in using provider-specific operators (43% vs 11% pass rate)
- **Syntax Knowledge:** Demonstrates strong understanding of modern Airflow 3.x API patterns

**Weaknesses - Root Cause Analysis:**

1. **Instruction Following (8% pass rate vs 15% baseline):** Training dataset exhibits poor diversity in numerical parameters—85.7% of examples use "20" as a dummy value across various contexts (e.g., "insert 20 records", "20 retries", "20 seconds"). The model overfitted to this pattern and fails to generalize to different numerical specifications.

2. **Hallucination Rate (6% pass rate vs 24% baseline):** Two primary causes:
   - **Data Leakage:** Training set included internal Airflow test files that import `tests_common.test_utils.system_tests` utilities. Model reproduces these non-production imports.
   - **Incomplete Knowledge:** Limited training examples for niche libraries (e.g., `airflow.timetables`, `airflow.example_dags.plugins`) cause the model to fabricate API interactions rather than admit uncertainty.

The subsequent cells provide concrete examples demonstrating each failure mode with side-by-side comparisons between ground truth, baseline, and fine-tuned outputs.

In [ ]:
EVAL_PROMPT_TEMPLATE = """
You are an expert Senior Apache Airflow Architect. Evaluate the following Airflow DAG code generated by an AI model based on a user instruction and the target airflow version with which the DAG code has been produced.

### Scoring Criteria & Examples

**1. Idiomatic Airflow (Score 0 or 1)**
* **Score 1 (Pass):** Uses specific Providers and Operators designed for the task.
    * *Example:* `from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator`
* **Score 0 (Fail):** Relies on generic "Pythonic" patterns where it wraps logic in a `PythonOperator` + Hook instead of using the native Operator.
    * *Example:* `def load(): hook = SnowflakeHook(...) \n PythonOperator(python_callable=load ...)`

**2. No Hallucination/Leakage (Score 0 or 1)**
* **Score 1 (Pass):** Code is clean, production-ready, and uses only standard Airflow libraries.
* **Score 0 (Fail):** Code exhibits any of the following:
    * Imports internal testing modules or test harness boilerplate (e.g., `from tests_common.test_utils.system_tests import get_test_run`, `test_run = get_test_run(dag)`).
    * Hallucinates non-existent modules, operators, or API methods (e.g., `GoogleCampaignManagerBatchInsertOperator` when only `BatchInsertConversionsOperator` exists).
    * Uses parameters that do not exist for the specified operator.

**3. Instruction Adherence (Score 0 or 1)**
* **Score 1 (Pass):** Fulfills the specific business logic requested (e.g., "load data AND validate").
* **Score 0 (Fail):** Misses a key step of the instruction.

---

### Task
USER INSTRUCTION:
{instruction}

TARGET AIRFLOW VERSION:
{airflow_version}

DAG CODE:
```python
{dag_content}
```


Evaluate the code based on the criteria above. Return valid JSON only.

{{{{
  "idiomatic_airflow": {{{{ "score": 0, "reasoning": "..." }}}}
  "no_hallucination": {{{{ "score": 0, "reasoning": "..." }}}},
  "instruction_adherence": {{{{ "score": 0, "reasoning": "..." }}}}
}}}}
"""

def prepare_llm_batch_requests(dags: List[Dict],
                                model_name: str, 
                                prompt_template: str = EVAL_PROMPT_TEMPLATE) -> List[Dict]:
    """Prepare batch requests for Claude LLM evaluation.
    
    Includes all DAGs with DAG generation requests (even if they failed parser validation).
    """
    batch_requests = []
    
    print(f"Preparing requests for all {len(dags)} DAGs...")
    
    skipped_non_dag = 0
    
    for idx, dag_record in enumerate(dags):
        
        system_message = dag_record.get('system', '')
        # Only include DAG generation requests (filter out other types)
        if not system_message.startswith("You are an expert Apache Airflow developer"):
            skipped_non_dag += 1
            continue
        
        # Extract metadata
        metadata = dag_record.get('metadata', {})
        airflow_version = metadata.get('airflow_version', 'Unknown')

        # Create prompt
        prompt = prompt_template.format(
            dag_content=extract_code(dag_record.get('code', '')), 
            instruction=dag_record.get('prompt', ''),
            airflow_version=airflow_version
        )
        
        # Create batch request
        request = {
            "custom_id": f"{model_name}_{idx}",
            "params": {
                "model": "claude-sonnet-4-5-20250929",
                "max_tokens": 2000,
                "temperature": 0.0,
                "messages": [{"role": "user", "content": prompt}]
            }
        }
        
        batch_requests.append(request)
    if skipped_non_dag > 0:
        print(f"Skipped {skipped_non_dag} non-DAG generation requests")
    
    return batch_requests

print("Preparing LLM evaluation batch requests (including DAGs that failed parser validation)...")


if ANTHROPIC_API_KEY:
    processor = ClaudeBatchProcessor(api_key=ANTHROPIC_API_KEY)
    
    # Prepare batches for full datasets
    print(f"Preparing evaluation batches...")
    ground_batch_requests = prepare_llm_batch_requests(
    ground_data, 
    "ground"
    )
    baseline_batch_requests = prepare_llm_batch_requests(
    baseline_data, 
    "baseline"
    )
    finetuned_batch_requests = prepare_llm_batch_requests(
        finetuned_data,
        "finetuned"
    )
    all_batch_requests = ground_batch_requests + baseline_batch_requests + finetuned_batch_requests
    
    print(f"✓ Prepared {len(all_batch_requests)} evaluation requests ({len(ground_batch_requests)} ground + {len(baseline_batch_requests)} baseline + {len(finetuned_batch_requests)} fine-tuned)")
else:
    print("⚠️ Skipping LLM evaluation setup:")
    if not ANTHROPIC_API_KEY:
        print("  - No ANTHROPIC_API_KEY found in environment")

Preparing LLM evaluation batch requests (including DAGs that failed parser validation)...
Preparing evaluation batches...
Preparing requests for all 412 DAGs...
Skipped 70 non-DAG generation requests
Preparing requests for all 412 DAGs...
Skipped 70 non-DAG generation requests
Preparing requests for all 412 DAGs...
Skipped 70 non-DAG generation requests
✓ Prepared 1026 evaluation requests (342 ground + 342 baseline + 342 fine-tuned)

In [41]:
# Execute Batch Processing and Parse Results
print("Submitting batch request to Claude API...")
print(f"This will evaluate {len(all_batch_requests)} DAGs using Claude Sonnet 4.5")
print()

# Submit batch
batch_id = processor.submit_batch(all_batch_requests)
print(f"Batch submitted: {batch_id}")
print()

2026-01-08 20:09:37,478 - INFO - 🚀 Submitting batch with 1026 requests...

Submitting batch request to Claude API...
This will evaluate 1026 DAGs using Claude Sonnet 4.5

2026-01-08 20:09:43,910 - INFO - HTTP Request: POST https://api.anthropic.com/v1/messages/batches?beta=true "HTTP/1.1 200 OK"
2026-01-08 20:09:43,914 - INFO - ✅ Batch submitted: msgbatch_01DFW8intELHUb6Mn8iHB2fP

Batch submitted: msgbatch_01DFW8intELHUb6Mn8iHB2fP

In [46]:
 # Wait for completion (can take 10-30 minutes for large batches)
print("⏳ Waiting for batch to complete (this may take 10-30 minutes)...")
batch = processor.wait_for_batch_completion('msgbatch_01DFW8intELHUb6Mn8iHB2fP') #batch_id)
print()

# Download results
print("📥 Downloading results...")
results = processor.download_batch_results(batch_id)
print(f"✓ Downloaded {len(results)} results")
print()

# Parse results into dataframe
print("📊 Parsing evaluation scores...")
llm_eval_results = []
parse_errors = 0

for result in results:
    if result['result']['type'] == 'succeeded':
        # Parse model name and dag_id from custom_id
        # Handle format: "baseline_123" or "finetuned_123"
        custom_id = result['custom_id']
        parts = custom_id.split('_')
        model_name = parts[0]  # 'ground', 'baseline' or 'finetuned'
        dag_id = int(parts[1])
        text = result['result']['message']['content'][0]['text']
        try:
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
                eval_data = json.loads(json_str)
            else:
                raise ValueError("No JSON object found in response")
            llm_eval_results.append({
                'model': model_name,
                'dag_id': dag_id,
                'idiomatic_airflow_score': eval_data['idiomatic_airflow']['score'],
                'idiomatic_airflow_reasoning': eval_data['idiomatic_airflow']['reasoning'],
                'no_hallucination_score': eval_data['no_hallucination']['score'],
                'no_hallucination_reasoning': eval_data['no_hallucination']['reasoning'],
                'instruction_adherence_score': eval_data['instruction_adherence']['score'],
                'instruction_adherence_reasoning': eval_data['instruction_adherence']['reasoning'],
            })
        except json.JSONDecodeError:
            parse_errors += 1
    elif result['result']['type'] == 'errored':
        parse_errors += 1


df_llm = pd.DataFrame(llm_eval_results)
print(f"✓ Parsed {len(llm_eval_results)} evaluation scores")
if parse_errors > 0:
    print(f"⚠️ {parse_errors} results had errors or couldn't be parsed")

# Display summary statistics
summary = df_llm.groupby('model').agg({
    'idiomatic_airflow_score': 'mean',
    'no_hallucination_score': 'mean',
    'instruction_adherence_score': 'mean'
}).round(2)

print("\nLLM Evaluation Summary (% rate):")
display(summary)
df_llm.to_csv('llm_eval.csv')

2026-01-09 08:58:30,365 - INFO - ⏳ Waiting for batch msgbatch_01DFW8intELHUb6Mn8iHB2fP...

⏳ Waiting for batch to complete (this may take 10-30 minutes)...

2026-01-09 08:58:30,641 - INFO - HTTP Request: GET https://api.anthropic.com/v1/messages/batches/msgbatch_01DFW8intELHUb6Mn8iHB2fP?beta=true "HTTP/1.1 200 OK"
2026-01-09 08:58:30,648 - INFO - 📊 Status: ended (elapsed: 0.3s)
2026-01-09 08:58:30,649 - INFO -    Progress: 1026/1026 (100.0%)
2026-01-09 08:58:30,649 - INFO - ✅ Batch completed with status: ended
2026-01-09 08:58:30,650 - INFO - ⬇️ Downloading results...
2026-01-09 08:58:30,827 - INFO - HTTP Request: GET https://api.anthropic.com/v1/messages/batches/msgbatch_01DFW8intELHUb6Mn8iHB2fP?beta=true "HTTP/1.1 200 OK"

📥 Downloading results...

2026-01-09 08:58:31,136 - INFO - HTTP Request: GET https://api.anthropic.com/v1/messages/batches/msgbatch_01DFW8intELHUb6Mn8iHB2fP/results "HTTP/1.1 200 OK"
2026-01-09 08:58:31,759 - INFO - 📥 Downloaded 1026 items

✓ Downloaded 1026 results

📊 Parsing evaluation scores...
✓ Parsed 1026 evaluation scores

LLM Evaluation Summary (% rate):

,idiomatic_airflow_score,no_hallucination_score,instruction_adherence_score
model,,,
baseline,0.07,0.28,0.15
finetuned,0.56,0.01,0.15
ground,0.92,0.12,0.89

### Success Case: Idiomatic Airflow Syntax

The fine-tuned model demonstrates superior knowledge of Airflow's provider ecosystem and operator patterns. This section showcases examples where the model correctly uses native operators instead of generic Python wrappers.

**Example DAG ID 3: Campaign Manager Operations**
- **Fine-tuned:** Adopts the idiomatic pattern of using native operators (e.g., `GoogleCampaignManagerRunReportOperator`).
  *Note: It attempted to use `GoogleCampaignManagerBatchInsertOperator`, which follows the correct provider naming convention but does not actually exist (the valid operator is `BatchInsertConversionsOperator`). This indicates the model has learned the "native operator" style strongly, even if it occasionally hallucinates class names.*
- **Baseline:** Falls back to `PythonOperator` wrapping `CampaignManagerHook` calls—a valid but verbose pattern that fails to leverage Airflow's higher-level abstractions.

In [48]:
# Set option to show full content of columns
pd.set_option('display.max_colwidth', None)
df_llm[df_llm.dag_id==3][['model','idiomatic_airflow_score','idiomatic_airflow_reasoning']]

,model,idiomatic_airflow_score,idiomatic_airflow_reasoning
2,ground,1,"The DAG uses native Airflow operators designed specifically for Campaign Manager tasks. It properly uses GoogleCampaignManagerInsertReportOperator, GoogleCampaignManagerRunReportOperator, GoogleCampaignManagerDownloadReportOperator, GoogleCampaignManagerBatchInsertConversionsOperator, GoogleCampaignManagerBatchUpdateConversionsOperator, and GoogleCampaignManagerReportSensor. These are all idiomatic Airflow operators from the google marketing platform provider rather than wrapping logic in PythonOperators with hooks."
344,baseline,0,"The code uses PythonOperator with placeholder functions instead of leveraging Airflow's Campaign Manager provider operators. Airflow has google.marketing_platform providers (which includes Campaign Manager/DCM operators) that should be used for idiomatic implementation. The code wraps what should be native operator calls in generic Python functions, which is the anti-pattern described in the scoring criteria."
686,finetuned,1,"The DAG uses native Campaign Manager operators from airflow.providers.google.marketing_platform.operators.campaign_manager throughout, including GoogleCampaignManagerListCampaignsOperator, GoogleCampaignManagerBatchInsertOperator, GoogleCampaignManagerRunReportOperator, etc. While there are a few PythonOperators used for data manipulation (list_account_csv, list_ads, join), these are used for orchestration logic rather than wrapping hooks, which is acceptable. The core Campaign Manager interactions all use proper operators."

### Failure Case 1: Dataset Overfitting and Poor Generalization

The finetuned model frequently defaults to AWS-specific operators even when the user instruction explicitly requests operations involving other cloud providers like Google Cloud (GCP) or Microsoft Azure.

**Root Cause**: Imbalanced Training Distribution Analysis of the training dataset reveals that ~20% of the records contain AWS-related keywords. In the world of Airflow examples, AWS is the "majority class." Because the model is small (1.5B parameters), it has a lower capacity for logical reasoning and instead relies on statistical frequency. It has learned that the most "likely" way to create a cloud bucket is via an S3 operator, effectively treating AWS as the "default" cloud.

**Example Case**: DAG ID 39: The model successfully identified the need for a "Create Bucket" and "Delete Bucket" task. However, instead of using AzureFileShareToGCSOperator, it used S3CreateBucketOperator.

In [63]:
pd.set_option('display.max_colwidth', None)
df_llm[df_llm.dag_id==39][['model','instruction_adherence_score','instruction_adherence_reasoning']]

,model,instruction_adherence_score,instruction_adherence_reasoning
30,ground,1,"The DAG fulfills all requirements from the user instruction: (1) demonstrates cross-cloud file transfer between Azure and Google Cloud using AzureFileShareToGCSOperator, (2) creates a destination GCS bucket, (3) transfers files from Azure FileShare to GCS, and (4) cleanly removes the temporary storage infrastructure with proper trigger rules to ensure cleanup happens regardless of transfer success/failure."
372,baseline,0,"While the DAG structure attempts to follow the instruction (create bucket, transfer files, cleanup), it fails to properly implement any of these steps. The bucket creation and cleanup tasks reference undefined functions, and the transfer operator is hallucinated. The instruction requires a working demonstration of cross-cloud file transfer between Azure and Google Cloud, but this code would not execute successfully. A proper implementation would need actual GCS bucket operators and the correct Azure-to-GCS transfer operator with proper implementations."
714,finetuned,0,"The instruction asks for a cross-cloud transfer between Azure and Google Cloud, with bucket creation and cleanup. However, the code incorrectly uses S3CreateBucketOperator and S3DeleteBucketOperator (AWS S3 operators) instead of GCS bucket operators (GCSCreateBucketOperator/GCSDeleteBucketOperator). The workflow should create a GCS bucket, not an S3 bucket, since the transfer is from Azure to GCS. This is a fundamental mismatch with the stated requirement of demonstrating Azure-to-GCP transfer capabilities."

In [62]:
train_ds = load_dataset(
    "andrea-t94/airflow-dag-dataset",
    split="test",
    download_mode="reuse_cache_if_exists"  # Use cached version if available
)
# Check how many records contain AWS related keywords in the prompt
count = 0
for entry in train_ds:
    messages = entry.get('messages', [])
    for msg in messages:
        if "AWS" in msg['content'] or "S3" in msg['content']:
            count += 1

print(f"Records containing AWS keywords in prompt: {count} out of {len(ground_data)} ({count/len(ground_data)*100:.1f}%)")

Generating train split:   0%|          | 0/7414 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/412 [00:00<?, ? examples/s]

Generating eval split:   0%|          | 0/412 [00:00<?, ? examples/s]

Records containing AWS keywords in prompt: 83 out of 412 (20.1%)

### Failure Case 2: Training Data Contamination with Internal Test Utilities

**Problem:** The fine-tuned model reproduces internal Airflow testing code that should never appear in production DAGs, resulting in a 6% hallucination-free pass rate (vs. 24% baseline).

**Root Cause Analysis (DAG ID 3):**
- **Contaminated Imports:** Both ground truth and fine-tuned model generate:
  ```python
  from tests_common.test_utils.system_tests import get_test_run
  test_run = get_test_run(dag)
  ```
- **Source:** Training dataset inadvertently included internal Airflow CI/CD test files used for system testing
- **Impact:** Claude evaluator correctly flags these as hallucinations since they reference non-public APIs unavailable in production Airflow installations

**Why This Matters:**
- Code would fail at import time: `ModuleNotFoundError: No module named 'tests_common'`
- Indicates the model cannot distinguish between test scaffolding and production code patterns
- Baseline model, lacking exposure to these internals, generates cleaner production-ready code

**Mitigation Strategies:**
1. **Data Filtering:** Implement strict preprocessing to exclude all files under `tests/`, `tests_common/`, or with `test_` prefixes
2. **Validation Pipeline:** Add automated checks to flag imports from non-production namespaces before adding examples to training set
3. **Synthetic Cleaning:** Post-process training examples to remove test harness boilerplate while preserving core DAG logic

In [65]:
pd.set_option('display.max_colwidth', None)
df_llm[df_llm.dag_id==3][['model','no_hallucination_score','no_hallucination_reasoning']]

,model,no_hallucination_score,no_hallucination_reasoning
2,ground,0,"The code contains clear test harness boilerplate and imports internal testing modules. Specifically, it imports 'from tests_common.test_utils.watcher import watcher' and 'from tests_common.test_utils.system_tests import get_test_run', and includes 'test_run = get_test_run(dag)' at the end. It also uses 'watcher()' in the DAG dependencies. Additionally, the docstring explicitly states 'This system test relies on...' indicating this is test code, not production-ready code."
344,baseline,0,"The code contains a critical error: 'batch_conversion_reporting_task' is referenced in the dependency chain (line with set_upstream) but is never defined. This variable doesn't exist in the code, making it non-executable. Additionally, 'airflow.operators.python_operator' is deprecated in Airflow 3.0.0 (should use 'airflow.operators.python' instead), and 'days_ago' is also deprecated in favor of datetime objects or pendulum."
686,finetuned,0,"The code explicitly imports test harness boilerplate at the end: 'from tests_common.test_utils.system_tests import get_test_run' and includes 'test_run = get_test_run(dag)'. This is internal testing infrastructure that should not be in production code. Additionally, many operators used in the code appear to be hallucinated - operators like GoogleCampaignManagerCreateGoogleCloudPlatformCredentialsOperator, GoogleCampaignManagerCreateCustomLabelOperator, GoogleCampaignManagerDeleteOperationOperator, and GoogleCampaignManagerListCampaignAsyncOperator do not exist in the standard Airflow Google Marketing Platform provider package. The code also references undefined variables like TEMPLATE_ID, OPERATION_ID, GCP_PROJECT_ID, and UPLOAD_FILE_PATH is used before being defined."

### Failure Case 3: Hallucinations from Insufficient Coverage of Niche APIs

**Problem:** When the finetuned model encounters specialized Airflow features that were sparse or uniquely implemented in the training set (such as Custom Timetables), it shifts from "following instructions" to "pattern guessing." It fabricates plausible-sounding but non-existent components and applies them with invalid logic.

**Example DAG ID 2:**

**Fine-tuned Model Hallucinations:**
- The model completely ignores the requested AfterWorkdayTimetable and instead hallucinates a TimeChartSensor from a fabricated module path (airflow.providers.standard.sensors.timechart). 
- Despite the prompt explicitly asking for a "custom timetable implementation," the model defaults to a standard-looking (but broken) task structure, failing to provide the actual class definition or logic requested.

**Major Causes of Failure**:
-  The finetuning process has taught the model the naming conventions of Airflow (e.g., airflow.providers.standard...) so well that when it doesn't know a specific class, it creates a "statistically probable" name (like TimeChartSensor) rather than admitting it doesn't know the custom class.
- Lack of "Implement-from-Scratch" Logic: Because the training data (official examples) often imports complex objects from internal plugins or paths (like airflow.example_dags.plugins), the model has not learned how to define new custom classes within the DAG file. It assumes all specialized logic must be imported from a provider.

In [66]:
pd.set_option('display.max_colwidth', None)
df_llm[df_llm.dag_id==2][['model','no_hallucination_score','no_hallucination_reasoning']]

,model,no_hallucination_score,no_hallucination_reasoning
1,ground,0,"The code imports 'AfterWorkdayTimetable' from 'airflow.example_dags.plugins.workday', which is an internal example/testing path within Airflow's codebase. This is not a production-ready import - it references example DAG plugins that would not exist in a standard Airflow deployment. Production code should either implement the custom timetable class directly in the project or import from a proper custom plugins directory, not from 'airflow.example_dags.plugins'."
343,baseline,0,"The code imports 'from airflow.timetables.after_workday import AfterWorkdayTimetable' which does not exist in standard Airflow. There is no built-in AfterWorkdayTimetable class in Airflow 3.0.0 or any version. This is a hallucinated/non-existent class. Additionally, 'timedelta' is used in default_args but never imported, causing a NameError."
685,finetuned,0,"The code imports 'airflow.providers.standard.sensors.timechart.TimeChartSensor' which does not exist in Airflow. This is a hallucinated module/class. There is no 'timechart' sensor in the standard providers package. Additionally, using a Sensor as a schedule parameter is not valid Airflow syntax."